defaults:
    extra-volume:
        size: 10 # GB
        dev: /dev/xvdh
        mnt: /mnt/xvdh
    vm:
        os: ubuntu-16.06
        size: tiny
        extra-volumes: []

p1:
    instance:
        type: vm
        os: ubuntu-18.04
