defaults:
   
    extra-volume:
        size: 10 # GB
        dev: /dev/xvdh
        mnt: /mnt/xvdh

    vm-image:
        id: ubuntu-18.04

    vpc-subnet-1:
        id: subnet-9e4603fa
        az: ap-southeast-2a

    vpc-subnet-2:
        id: subnet-0fc9a679
        az: ap-southeast-2b

    vpc:
        id: vpc-67e85103
        subnet1:
            type: vpc-subnet-1
        subnet2:
            type: vpc-subnet-2

    ec2:
        image:
            type: vm-image
        size: t2.nano
        ports:
            - 22 # ssh
        region: ap-southeast-2
        extra-volumes: []
        vpc:
            type: vpc

    actual: {}

    project-config:
        project-formula-url: null # repository for project formula
        private-formula-url: git@bitbucket.org:lskibinski/base-private-formula # repository for private formula
        formula-dependencies: []

    vagrant:
        box: "archlinux/archlinux"
        # TODO; CPU, RAM

base: []

base-private: []

# demo, temporary, remove when things are stable
simple-ec2:
    -   
        type: ec2
        image:
            id: ubuntu-16.04
    -
        type: project-config
        project-formula-url: git@bitbucket.org:lskibinski/salt-vagrant-arch
    -
        type: vagrant

# needs an ec2+s3 bucket
wowprj:
    -
        type: project-config
        project-formula-url: git@bitbucket.org:lskibinski/wowprj
    -
        type: vagrant

work:
    - 
        type: actual

home:
    -
        type: actual

mail:
    -
        type: vagrant
        box: bento/ubuntu-18.04
    -
        type: project-config
        project-formula-url: git@bitbucket.org:lskibinski/mail-formula
        formula-dependencies:
            #- git@bitbucket.org:lskibinski/base-formula
            - git@github.com:elifesciences/builder-base-formula
